---

require:
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: true

Bundler/GemFilename:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ArrayAlignment:
  Enabled: true

Layout/AssignmentIndentation:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  ForceEqualSignAlignment: false
  AllowForAlignment: false

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/LeadingEmptyLines:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/ParameterAlignment:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 150

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/NoExpectationExample:
  Enabled: false

Style/RedundantBegin:
  Enabled: true

Style/RedundantCondition:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
