name: Publish to RubyGems
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+* # should only run when the tags matches sematic versioning
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        set-safe-directory: false
    - name: Release Gem
      uses: powerhome/publish-rubygems-action@git-safe-directory
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
